package olgababeeva.homework.elegion.myapplication.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import olgababeeva.homework.elegion.myapplication.model.recipe;
import olgababeeva.homework.elegion.myapplication.model.ingredients;

import olgababeeva.homework.elegion.myapplication.model.recipeDao;
import olgababeeva.homework.elegion.myapplication.model.ingredientsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recipeDaoConfig;
    private final DaoConfig ingredientsDaoConfig;

    private final recipeDao recipeDao;
    private final ingredientsDao ingredientsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recipeDaoConfig = daoConfigMap.get(recipeDao.class).clone();
        recipeDaoConfig.initIdentityScope(type);

        ingredientsDaoConfig = daoConfigMap.get(ingredientsDao.class).clone();
        ingredientsDaoConfig.initIdentityScope(type);

        recipeDao = new recipeDao(recipeDaoConfig, this);
        ingredientsDao = new ingredientsDao(ingredientsDaoConfig, this);

        registerDao(recipe.class, recipeDao);
        registerDao(ingredients.class, ingredientsDao);
    }
    
    public void clear() {
        recipeDaoConfig.getIdentityScope().clear();
        ingredientsDaoConfig.getIdentityScope().clear();
    }

    public recipeDao getRecipeDao() {
        return recipeDao;
    }

    public ingredientsDao getIngredientsDao() {
        return ingredientsDao;
    }

}
