package olgababeeva.homework.elegion.myapplication.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INGREDIENTS".
 */
public class ingredients {

    private Long id;
    private String name;
    private String recipe_id;

    public ingredients() {
    }

    public ingredients(Long id) {
        this.id = id;
    }

    public ingredients(Long id, String name, String recipe_id) {
        this.id = id;
        this.name = name;
        this.recipe_id = recipe_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRecipe_id() {
        return recipe_id;
    }

    public void setRecipe_id(String recipe_id) {
        this.recipe_id = recipe_id;
    }

}
