package olgababeeva.homework.elegion.myapplication.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECIPE".
 */
public class recipe {

    private Long id;
    private String text;
    private Long likes;

    public recipe() {
    }

    public recipe(Long id) {
        this.id = id;
    }

    public recipe(Long id, String text, Long likes) {
        this.id = id;
        this.text = text;
        this.likes = likes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Long getLikes() {
        return likes;
    }

    public void setLikes(Long likes) {
        this.likes = likes;
    }

}
